CC = gcc
CFLAGS = -Wall -pedantic -std=c11
NAME = client
OBJS = $(NAME).o 

.PHONY: default clean

default: $(NAME)

%.o: %.c
	$(CC) -c $(CFLAGS) $< -o $@

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^

clean:
	rm -f $(NAME) $(OBJS)
